### ISSUE TITLE
Java 7/8 version mismatch

### ISSUE THREAD

**Issue by mxhm** [genepi/imputationserver-docker#6]
This might be more related to the genepi/cdh5-hadoop-mrv1 Dockerfile, but I had to manually symlink default-java -> java-8-openjdk-amd64 in `/usr/lib/jvm` for Hadoop jobs to complete successfully. In the docker image, default-java points to java-7-openjdk-amd64.

**Comment by seppinho** [comment]
Can you send me the command how you run the docker container?

**Comment by mxhm** [comment]
I started the docker instance with this command: `docker run -d -p 7585:80  -v /path/to/michigan_imputation_server_data/:/data/ genepi/imputationserver:v1.2.5-1`. I just changed the port and use a host volume to exchange data with the docker instance.

**Comment by seppinho** [comment]
Awesome. That was really helpful! We added your fix to the base image and latest version (1.2.7) should work again. Not sure why this caused the problem. Really appreciate your help.

**Comment by mxhm** [comment]
No problem! Thanks for the docker images, they are really useful.
